// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLb-eGMbfvrYoG3z01If0c9vujRV9LOM',
    appId: '1:834201404220:web:0349e0100fd01aa2939439',
    messagingSenderId: '834201404220',
    projectId: 'solidwaste4c',
    authDomain: 'solidwaste4c.firebaseapp.com',
    storageBucket: 'solidwaste4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGNwugfSOTfkPayA8s31lhaJdpw7O8VpM',
    appId: '1:834201404220:android:d7e770aa5d7700dd939439',
    messagingSenderId: '834201404220',
    projectId: 'solidwaste4c',
    storageBucket: 'solidwaste4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDegw4KEWk9vq6bTT3thrx10My8gNQQxXQ',
    appId: '1:834201404220:ios:673fda65e8f78e52939439',
    messagingSenderId: '834201404220',
    projectId: 'solidwaste4c',
    storageBucket: 'solidwaste4c.appspot.com',
    iosBundleId: 'com.example.capstoneapp',
  );
}
